# Generated by Django 3.0.2 on 2020-02-02 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cocktail',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('ingredienti', models.TextField()),
                ('prezzo', models.FloatField()),
            ],
            options={
                'db_table': 'Cocktail',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('cognome', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('telefono', models.BigIntegerField()),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Persona',
            },
        ),
        migrations.CreateModel(
            name='Barista',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='bar.Persona')),
            ],
            options={
                'db_table': 'Barista',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='bar.Persona')),
            ],
            options={
                'db_table': 'Cliente',
            },
        ),
        migrations.CreateModel(
            name='CodicePrenotazione',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('codice', models.BigIntegerField()),
                ('fk_id_barista', models.ForeignKey(blank=True, db_column='fk_id_barista', null=True, on_delete=django.db.models.deletion.CASCADE, to='bar.Barista')),
            ],
            options={
                'db_table': 'Codice_prenotazione',
            },
        ),
        migrations.CreateModel(
            name='ClienteOrdinaCocktailRicevendoCodicePrenotazione',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('data', models.CharField(max_length=100)),
                ('fk_id_cocktail', models.ForeignKey(db_column='fk_id_cocktail', on_delete=django.db.models.deletion.CASCADE, to='bar.Cocktail')),
                ('fk_id_codice_prenotazione', models.ForeignKey(db_column='fk_id_codice_prenotazione', on_delete=django.db.models.deletion.CASCADE, to='bar.CodicePrenotazione')),
                ('fk_id_cliente', models.ForeignKey(db_column='fk_id_cliente', on_delete=django.db.models.deletion.CASCADE, to='bar.Cliente')),
            ],
            options={
                'db_table': 'Cliente_ordina_cocktail_ricevendo_codice_prenotazione',
            },
        ),
        migrations.CreateModel(
            name='BaristaGestisceCocktail',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fk_id_cocktail', models.ForeignKey(db_column='fk_id_cocktail', on_delete=django.db.models.deletion.CASCADE, to='bar.Cocktail')),
                ('fk_id_barista', models.ForeignKey(db_column='fk_id_barista', on_delete=django.db.models.deletion.CASCADE, to='bar.Barista')),
            ],
            options={
                'db_table': 'Barista_gestisce_cocktail',
            },
        ),
    ]
