# Generated by Django 3.0.3 on 2020-02-14 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baristagestiscecocktail',
            name='azione',
            field=models.CharField(default='azione', max_length=100),
            preserve_default=False,
        ),
    ]
