# Generated by Django 3.0.3 on 2020-04-09 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0002_baristagestiscecocktail_azione'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baristagestiscecocktail',
            name='fk_id_cocktail',
            field=models.ForeignKey(db_column='fk_id_cocktail', on_delete=models.SET(0), to='bar.Cocktail'),
        ),
        migrations.AlterField(
            model_name='clienteordinacocktailricevendocodiceprenotazione',
            name='fk_id_cocktail',
            field=models.ForeignKey(db_column='fk_id_cocktail', on_delete=models.SET(0), to='bar.Cocktail'),
        ),
    ]
