# Generated by Django 3.0.3 on 2020-04-09 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0003_auto_20200409_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baristagestiscecocktail',
            name='fk_id_cocktail',
            field=models.ForeignKey(db_column='fk_id_cocktail', on_delete=django.db.models.deletion.CASCADE, to='bar.Cocktail'),
        ),
        migrations.AlterField(
            model_name='clienteordinacocktailricevendocodiceprenotazione',
            name='fk_id_cocktail',
            field=models.ForeignKey(db_column='fk_id_cocktail', on_delete=django.db.models.deletion.CASCADE, to='bar.Cocktail'),
        ),
    ]
